name: candid
version: git
summary: Candid Identity Manager
description: Candid Identity Manager
grade: stable
confinement: strict

apps:
  candidsrv:
    command: wrappers/candidsrv
    daemon: simple
    plugs:
     - network
     - network-bind
  candid:
    command: wrappers/candid
    plugs:
     - home
     - network

parts:
  # Candid
  candid:
    plugin: x-go-modules
    source: .
    source-type: git
    build-packages:
     - bzr
    go-packages:
     - ./cmd/candid
     - ./cmd/candidsrv
    prime:
     - bin/candid
     - bin/candidsrv
    override-build: |
      set -e
      GIT_COMMIT=`git rev-parse --verify HEAD`
      GIT_VERSION=`git describe --dirty`
      for cmd in go.gofmt gofmt
      do
          $cmd -r "unknownVersion -> Version{GitCommit: \"${GIT_COMMIT}\", Version: \"${GIT_VERSION}\",}" version/init.go.tmpl > version/init.go && break
      done
      snapcraftctl build

  bakery-keygen:
    plugin: x-go-modules
    source: https://github.com/go-macaroon-bakery/macaroon-bakery
    source-type: git
    source-tag: v2.0.0
    build-snaps:
      - go
    go-packages:
      - ./cmd/bakery-keygen
    prime:
      - bin/bakery-keygen

  jq:
    plugin: dump
    stage-packages:
     - jq
    organize:
      usr/bin/: bin/
      usr/lib/: lib/
    prime:
     - bin/jq
     - lib/*/libonig.so*

  snapcraft:
    plugin: dump
    source: snap/
    prime:
     - config
     - wrappers

  www:
    plugin: dump
    source: .
    organize:
      static: www/static/
      templates: www/templates/
    prime:
     - www
